name: gh-pages

run-name: run name(gh-pages)

on: workflow_dispatch

jobs:
  build:
    name: build dist
    permissions:
      contents: read
      id-token: write
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with: 
          ref: gh-pages

      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
  
      - run: |
          pnpm i
          npm run build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: dist  # 与 deploy-pages 中的 artifact_name 保持一致
          path: dist

  deploy:
    name: deploy githupage

    environment: github-pages
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: dist
          token: ${{ secrets.GH_PAGE }}



    
        

    

